# Services
services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Factories
    Esit\Valueobjects\Classes\Database\Services\Factories\DatabaseFactory:
        public: true

    Esit\Valueobjects\Classes\Database\Services\Factories\SchemaManagerFactory: ~

    # Validators
    Esit\Valueobjects\Classes\Database\Services\Validators\DatabasenameValidator: ~

    Esit\Valueobjects\Classes\Database\Services\Validators\FieldnameValidator: ~

    Esit\Valueobjects\Classes\Database\Services\Validators\TablenameValidator: ~
