# Services
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Esit\Valueobjects\Classes\Ip\Services\Factories\IpFactory:

    Esit\Valueobjects\Classes\Ip\Services\Validators\IpValidator:
