# Services
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Esit\Valueobjects\Classes\Isbn\Services\Factories\IsbnFactory:

    Esit\Valueobjects\Classes\Isbn\Services\Validators\IsbnValidator:
